[project]
name = "coroebus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "plotly>=6.5.1",
    "shiny>=1.5.1",
    "shinylive>=0.8.5",
    "shinywidgets>=0.4.0",
]
